FROM ubuntu
RUN  apt update &&  apt install -y apache2 
#ENV APACHE_RUN_USER www-data
#ENV APACHE_RUN_GROUP www-data
#ENV APACHE_LOG_DIR /var/log/apache2
#ENV APACHE_RUN_DIR /var/run/apache2
EXPOSE 8081
#CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]
CMD apachectl -D FOREGROUND
